### ISSUE TITLE
Docs for running simulation

### ISSUE THREAD

**Issue by haraldng** [vitorenesduarte/fantoch#257]
Is there any documentation/tutorial on how to run the simulator locally?

**Comment by vitorenesduarte** [comment]
Not really. This is the binary we used for simulations: https://github.com/vitorenesduarte/fantoch/blob/main/fantoch_ps/src/bin/simulation.rs

I don't remember much anymore, but I think that this can be run with `cargo run -p fantoch_ps --bin simulation`.

Let me know if this doesn't work or if you have any other questions.

**Comment by haraldng** [comment]
I had to change the path here: https://github.com/vitorenesduarte/fantoch/blob/main/fantoch_ps/src/bin/simulation.rs#L17

But otherwise, it seems to work. Thanks!

**Comment by vitorenesduarte** [comment]
Glad to hear that!
